kind: Service
apiVersion: v1
metadata:
  name: winedemo
  namespace: namespace-winedemo
  labels:
    app: winedemo
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "100Mbps"
spec:
  type: LoadBalancer
  selector:
    app: winedemo
  ports:
  - port: 80
    targetPort: 3000
    name: http
#  - port: 443
#    targetPort: 3000
#    name: https  
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: winedemo
  namespace: namespace-winedemo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: winedemo
  template:
    metadata:
      labels:
        app: winedemo
        version: v1
    spec:
      containers:
      - name: winedemo
        image:  eu-frankfurt-1.ocir.io/emeaseitalysandbox/winedemo:winedemo
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
        env:
        - name: NODE_ORACLEDB_USER
          value: "ADMIN"
        - name: NODE_ORACLEDB_PASSWORD
          value: "DataBase##11"
#        - name: NODE_ORACLEDB_CONNECTIONSTRING
#          value: "jsonattack_high"        
#        - name: TNS_ADMIN
#          value: "/wallet"        
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: secret
#      nodeSelector: 
#        name: PRO
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: winedemo
  namespace: namespace-winedemo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: winedemo
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 1k
---
